name: CI

on:
  pull_request:

permissions:
  contents: read

jobs:
  unit-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [18]
      fail-fast: false
    timeout-minutes: 10

    name: 'Build & Unit Test: node-${{ matrix.node_version }}, ${{ matrix.os }}'
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          # Required for docs/versions tests
          fetch-depth: 0

      - name: Install deps
        run: yarn install

      - name: Test
        run: yarn run test

      - name: Build
        run: yarn run build
